#Requires -Version 5.1
<#
.SYNOPSIS
  Rebuild coast-overlay-lite.js from OpenStreetMap coastline (NOT coast-geo.js).

.DESCRIPTION
  1) Optionally fetch Overpass natural=coastline into coast-osm.json
  2) Emit coast-osm-ways.js (compact JS for WSH)
  3) Run build-coast-overlay-lite.js (cscript) to chain/decimate/write overlay

.EXAMPLE
  powershell -File build-coast-overlay-lite.ps1
  powershell -File build-coast-overlay-lite.ps1 -Fetch
#>
param(
  [switch]$Fetch,
  [string]$OsmJson = ''
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
Set-Location $root

function FetchOsm([string]$outPath) {
  $queryPath = Join-Path $root 'overpass-query.txt'
  if (-not (Test-Path $queryPath)) {
    @"
[out:json][timeout:120];
(
  way["natural"="coastline"](32.95,-120.20,34.15,-117.55);
);
out geom;
"@ | Set-Content -Path $queryPath -Encoding ASCII
  }
  $mirrors = @(
    'https://maps.mail.ru/osm/tools/overpass/api/interpreter',
    'https://overpass.kumi.systems/api/interpreter',
    'https://overpass-api.de/api/interpreter'
  )
  $tmp = Join-Path $root 'coast-osm-fetch.tmp.json'
  foreach ($m in $mirrors) {
    Write-Host "Fetching Overpass: $m"
    & curl.exe -s -A 'SoCalBoatBoard/1.0 (coast overlay rebuild)' -X POST $m `
      --data-binary "@$queryPath" -o $tmp -w "HTTP:%{http_code} SIZE:%{size_download}`n" --max-time 180
    if ((Test-Path $tmp) -and ((Get-Item $tmp).Length -gt 500000)) {
      Move-Item -Force $tmp $outPath
      Write-Host "Wrote $outPath"
      return
    }
  }
  throw 'All Overpass mirrors failed; keep an existing coast-osm.json or retry later.'
}

function ExportWaysJs([string]$osmPath, [string]$outJs) {
  Write-Host "Loading $osmPath ..."
  $json = Get-Content $osmPath -Raw | ConvertFrom-Json
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine('/* OSM natural=coastline ways — generated by build-coast-overlay-lite.ps1; do not edit. */')
  [void]$sb.Append('var COAST_OSM_WAYS=[')
  $first = $true
  $wayCount = 0
  $nodeCount = 0
  foreach ($el in $json.elements) {
    if ($el.type -ne 'way') { continue }
    if ($null -eq $el.geometry -or $el.geometry.Count -lt 2) { continue }
    if (-not $first) { [void]$sb.Append(',') }
    $first = $false
    [void]$sb.Append('{id:"')
    [void]$sb.Append([string]$el.id)
    [void]$sb.Append('",pts:[')
    $pf = $true
    foreach ($g in $el.geometry) {
      if (-not $pf) { [void]$sb.Append(',') }
      $pf = $false
      [void]$sb.Append('{lat:')
      [void]$sb.Append(([double]$g.lat).ToString([System.Globalization.CultureInfo]::InvariantCulture))
      [void]$sb.Append(',lon:')
      [void]$sb.Append(([double]$g.lon).ToString([System.Globalization.CultureInfo]::InvariantCulture))
      [void]$sb.Append('}')
      $nodeCount++
    }
    [void]$sb.Append(']}')
    $wayCount++
  }
  [void]$sb.AppendLine('];')
  [System.IO.File]::WriteAllText($outJs, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
  Write-Host ("Wrote coast-osm-ways.js: {0} ways, {1} nodes" -f $wayCount, $nodeCount)
}

$osmPath = if ($OsmJson) { $OsmJson } else { Join-Path $root 'coast-osm.json' }
if ($Fetch -or -not (Test-Path $osmPath)) {
  FetchOsm $osmPath
}
if (-not (Test-Path $osmPath)) {
  throw "Missing $osmPath - run with -Fetch or place Overpass JSON there."
}

$waysJs = Join-Path $root 'coast-osm-ways.js'
ExportWaysJs $osmPath $waysJs

Write-Host 'Building coast-overlay-lite.js via cscript ...'
& cscript //Nologo (Join-Path $root 'build-coast-overlay-lite.js')
if ($LASTEXITCODE -ne 0) { throw "build-coast-overlay-lite.js failed with exit $LASTEXITCODE" }
